name: Linux

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-test:
    name: Linux tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --all-features
